app/aplicaciones/erp/urls.py
from django.urls import  path

from aplicaciones.erp.api.api import CategoryAPIView, DetailCategoryAPIView
from aplicaciones.erp.views.category.views import  *
from aplicaciones.erp.views.client.views import ClientListView
from aplicaciones.erp.views.dashboard.views import DashboardView
from aplicaciones.erp.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from aplicaciones.erp.views.test.views import TestView

app_name = 'erp'
urlpatterns = [


    path('category/prueba', category_list, name='category'),

    path('category/list', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # PRODUCT
    path('product/list', ProductListView.as_view(), name='product_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    # CLIENT
    path('client/list', ClientListView.as_view(), name='client_list'),

    # PRUEBAS APIS
    path('categoria/', CategoryAPIView.as_view(),name="category_api" ),
    path('categoria/detail/',DetailCategoryAPIView.as_view(),name="category_detail_api"),



    # test
    path('test/', TestView.as_view(), name="test_view"),

    # FORM VIEWS
    path('category/form/',CategoryFormView.as_view(),name="category_form"),

    # DASHBOAR
    path('dashboard/',DashboardView.as_view(),name="dashboard")
]

app/app/urls.py
from unicodedata import name

from django.contrib import admin
from django.urls import path, include

from aplicaciones.homepage.views import IndexView
from aplicaciones.login.views import LoginForView, LoginForView2
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('erp/', include('aplicaciones.erp.urls')),
    path('login/', include('aplicaciones.login.urls')),
    path('', IndexView.as_view())

]
urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

app/aplicaciones/erp/views/category/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from aplicaciones.erp.forms import CategoryForm
from aplicaciones.erp.mixins import IsSuperuserMixin, ValidatePermissionRequiredMixin
from aplicaciones.erp.models import Category


@method_decorator(csrf_exempt)
def category_list(request):
    print(request.POST)
    print(request.POST.getlist('download_inv[0]'))
    return JsonResponse(request.POST)


# Hace lo mismo que category list, pero de una forma mas automatica, sin embargo
# la data que mandamos no, es por eso que debemos sobreescribir algunos metodos para lograrlo

class CategoryListView(LoginRequiredMixin,ValidatePermissionRequiredMixin, ListView):
    model = Category
    template_name = 'category/list.html'
    permission_required = 'erp.add_sale'

    @method_decorator(csrf_exempt)
    # @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    # ESTE POST NO LO ESTAMOS USANDO
    def post(self, request, *args, **kwargs):
        data = {}
        print(request.POST)
        try:
            action = request.POST['action']
            # Vamos a consultar todos los datos, y los vamos a ir guardando en un array
            # iteramos esa consulta, y con el toJSON de esa entidad,
            # podremos conseguir en formato JSON cada uno de los registros-
            if action == 'getdata':
                # Una coleccion
                data = []
                for i in Category.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Ha ocurrido un error'

        except Exception as e:
            data['error'] = "NO HAY ACTION"
        #     safe= False, nos permite mandar cualquier objeto, diccionario de datos, que tengan el formato dict
        #     pues este es el unico que permite JsonResponse, en todo caso, nos mandara error-
        return JsonResponse(data, safe=False)

    # Al sobreescribir este metodo, le pasamos datos en un diccionario que podemos usar en el template
    # De esta forma, se convierte un poco dinamico, pues cambia dependiendo del list donde nos encontremos-
    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        context['categorias'] = Category.objects.all()
        context['title'] = "Registros"
        context['url_form'] = reverse_lazy('erp:category_create')
        context['url_pattern'] = reverse_lazy('erp:category_list')

        return context


class CategoryCreateView(ValidatePermissionRequiredMixin, CreateView):
    permission_required = 'erp.add_category'
    url_redirect = reverse_lazy('erp:category_list')
    model = Category
    form_class = CategoryForm
    template_name = 'category/create.html'
    # Colocale erp:
    # Ya que son la urls que estan dentro de la app erp
    success_url = reverse_lazy('erp:category_list')

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'add':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    # """
    #     # Sobreescribimos el metodo post, para asi poder revisar los errores (mas que nada comprender, ya que no es necesario)  ,
    #     # como el colocar la misma palabra para nombre, en caso que este se repita
    #     def post(self, request, *args, **kwargs):
    #         print(request.POST)
    #         # De la data que mandamos,paso primero por esta vista de clase, la cual le mando el
    #         # formulario que creamos con ModelForm
    #         # Por lo tanto, al guardar volvera a entrar se ira a su metodo post, pero ahora ya lo
    #         # estamos sobreescribiendo,y vamos a capturar validaciones
    #         # Para eso, capturamos el post y le mandamos la data a clase del formulario
    #         # Posteriormente preguntamos si es valido, en ese caso nos retorne a la pagina donde esta el success url-
    #         form = CategoryForm(request.POST)
    #         if form.is_valid():
    #             form.save()
    #             return HttpResponseRedirect(self.success_url)
    #         # Por otro lado, en caso contrario, deberemos renderizar nuevamente el template
    #         # Pero sera necesario mandarle los datos del content text-
    #         self.object = None
    #         context = self.get_context_data(**kwargs)
    #         context['form']= form
    #
    #         return render(request, self.template_name,context)
    # """
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = "Crear categoria"
        context['list_url'] = self.success_url
        context['action'] = 'add'

        return context


class CategoryUpdateView(UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = 'category/create.html'
    # Colocale erp:
    # Ya que son la urls que estan dentro de la app erp
    success_url = reverse_lazy('erp:category_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'edit':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'Sin opcion'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Edicion de categoria"
        context['list_url'] = self.success_url
        context['action'] = 'edit'

        return context


class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'category/delete.html'
    success_url = reverse_lazy('erp:category_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = " ¿Seguro que quiere borrar el siguiente registro?"
        context['list_url'] = self.success_url
        context['name'] = self.get_object().name

        return context


class CategoryFormView(FormView):
    # Solo le pasamos el form, no el modelo, asi trabaja esta vista de clase
    form_class = CategoryForm
    template_name = 'category/create.html'
    success_url = reverse_lazy('erp:category_list')

    def form_valid(self, form):
        print(form.is_valid())
        print(form)
        return super().form_valid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "FORM | CATEGORIA"
        context['list_url'] = self.success_url
        context['action'] = 'add'

        return context

app/aplicaciones/erp/views/client/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from aplicaciones.erp.forms import ClientForm
from aplicaciones.erp.mixins import ValidatePermissionRequiredMixin
from aplicaciones.erp.models import Client, Category
from django.contrib import  messages


class ClientListView(LoginRequiredMixin,ValidatePermissionRequiredMixin,TemplateView):
    template_name = 'client/list.html'
    # LO QUE SIGNIFICA QUE, OBLIGA A QUE EL USUARIO TENGA ESTOS PERMISOS PARA ASI ACCEDER A LA PAGINA
    # Es decir, si el usuario entra en esa vista, no es que si no tiene el permiso de ver, no pueda entrar
    # Si no que yo aqui agrego los permisos a los cuales es necesario que el usuario tenga acceso
    #
    permission_required = ('erp.add_client','erp.change_client')
    @method_decorator(csrf_exempt)
    # @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        print(request.POST)
        try:
            action = request.POST['action']
            if action == 'getdata':
                data = []
                for i in Client.objects.all():
                    data.append(i.toJSON())
            elif action == 'add':
                cli = Client()
                cli.names = request.POST['names']
                cli.surnames = request.POST['surnames']
                cli.dni = request.POST['dni']
                cli.date_birthday = request.POST['date_birthday']
                cli.address = request.POST['address']
                cli.gender = request.POST['gender']
                cli.save()
            elif action == 'edit':
                cli = Client.objects.get(pk=request.POST['id'])
                cli.names = request.POST['names']
                cli.surnames = request.POST['surnames']
                cli.dni = request.POST['dni']
                cli.date_birthday = request.POST['date_birthday']
                cli.address = request.POST['address']
                cli.gender = request.POST['gender']
                cli.save()
            elif action == 'del':
                cli = Client.objects.get(pk=request.POST['id'])
                cli.delete()
            elif action == 'autocomplete':
                data = []
                # PARA  EL AUTOCOMPLETE, DEBE IR COMO JSON, MAS QUE NADA  EL VALUE, Q ES EL VALOR Q VA A TOMAR
                for i in Client.objects.filter(names__icontains=request.POST['term']):
                    item = i.toJSON()
                    item['value'] = i.names
                    data.append(item)
            else:
                data['error'] = 'Ha ocurrido un error'

        except Exception as e:
            data['error'] = "NO HAY ACTION"
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super(ClientListView, self).get_context_data(**kwargs)
        # context['clientes'] = Client.objects.all()
        context['title'] = "Registros"
        context['url_pattern'] = reverse_lazy('erp:client_list')
        context['form'] = ClientForm()
        return context

app/aplicaciones/erp/views/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import  TemplateView


class DashboardView(LoginRequiredMixin,TemplateView):
    template_name = 'dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['panel'] = 'Panel administrador'
        return context

app/aplicaciones/erp/templates/client/list.html
{% extends 'list.html' %}
{% load widget_tweaks %}
{% load static %}
{% block head_list %}
    <script src="{% static 'client/js/list.js' %}"></script>
{% endblock %}
{% block columns %}
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>DNI</th>
        <th>Cumpleaños</th>
        <th>Direccion</th>
        <th>Sexo</th>
    </tr>
{% endblock %}
{% block rows %}
    {#    {% for cat in object_list %}#}
    {#        <tr>#}
    {#            <td>{{ cat.id }}</td>#}
    {#            <td>{{ cat.name }}</td>#}
    {#            <td> <strong>{{ cat.desc }}</strong></td>#}
    {#            <td>#}
    {#                <a href="{% url 'erp:category_update' cat.id %}" class="btn  btn-warning btn-xs"><i class="fa fa-edit"></i>#}
    {#                </a>#}
    {#                <a href="{% url 'erp:category_delete' cat.id %}" class="btn  btn-danger btn-xs"><i class="fa fa-trash"></i>#}
    {#                </a>#}
    {#            </td>#}
    {#        </tr>#}
    {#    {% endfor %}#}
{% endblock %}
{#SOBRESCRIBIMOS EL BLOCK DE VBUTTONS, YA QUE AQUI TENDRA  OTRO COMPORTAMIENTO#}
{% block buttons_list %}
    <a class="btn btn-warning text-dark btn-Test mr-2 btnAdd"><i
            class="fa fa-plus-square mr-2" aria-hidden="true"></i>Agregar</a>
    <a href="{{ url_pattern }}" class="btn btn-warning text-dark btn-Test"><i
            class="fa fa-refresh mr-2"></i>Actualizar</a>
{% endblock %}

{#No usaremos el JS de la plantilla en el template, puesto que usaremos la que se crea#}
{#en el js al cargar nuestra pagina#}
{% block javascript %}
    <!-- Modal -->
    <div class="modal fade" id="myModalClient" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <form method="post" action="." enctype="multipart/form-data" id="form">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        {#                        LE DEJAMOS ID, PARA QUE PUEDA SER DINAMICO EL TITULO DEL MODAL, Y SU ICONO#}
                        <h5 class="modal-title" id="title-modal"><i
                                class="" aria-hidden="true"></i><span>PROBANDO</span></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input name="action" type="hidden" value="add">
{#                    ES NECESARIO MANDAR ESTE ID#}
                        <input name="id" type="hidden" value="0">
                        {% for field in form.visible_fields %}

                            <div class="form-group">
                                <label>{{ field.label }} </label>
                                {# De esta manera realizamos la misma funcion que con el for en el constructor del formulario:))                           #}
                                {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                            </div>

                        {% endfor %}
                    </div>
                    <div class="modal-footer">
{#                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>#}
                        <button type="submit" class="btn btn-primary btn-lg btn-block">Guardar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock %}