app/aplicaciones/erp/urls.py
from django.urls import  path

from aplicaciones.erp.api.api import CategoryAPIView, DetailCategoryAPIView
from aplicaciones.erp.views.category.views import  *
from aplicaciones.erp.views.client.views import ClientListView
from aplicaciones.erp.views.dashboard.views import DashboardView
from aplicaciones.erp.views.product.views import ProductListView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView
from aplicaciones.erp.views.test.views import TestView

app_name = 'erp'
urlpatterns = [


    path('category/prueba', category_list, name='category'),

    path('category/list', CategoryListView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # PRODUCT
    path('product/list', ProductListView.as_view(), name='product_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    # CLIENT
    path('client/list', ClientListView.as_view(), name='client_list'),

    # PRUEBAS APIS
    path('categoria/', CategoryAPIView.as_view(),name="category_api" ),
    path('categoria/detail/',DetailCategoryAPIView.as_view(),name="category_detail_api"),



    # test
    path('test/', TestView.as_view(), name="test_view"),

    # FORM VIEWS
    path('category/form/',CategoryFormView.as_view(),name="category_form"),

    # DASHBOAR
    path('dashboard/',DashboardView.as_view(),name="dashboard")
]

app/app/urls.py
from unicodedata import name

from django.contrib import admin
from django.urls import path, include

from aplicaciones.homepage.views import IndexView
from aplicaciones.login.views import LoginForView, LoginForView2
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('admin/', admin.site.urls),
    path('erp/', include('aplicaciones.erp.urls')),
    path('login/', include('aplicaciones.login.urls')),
    path('', IndexView.as_view())

]
urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

app/templates/vtc/aside.html
{% load static %}
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-red elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{% static 'img/shopping_cart_white_48dp.svg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Sofenix</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{  request.user.get_image }}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ user.username }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item ">
            <a href="#" class="nav-link">
                <img  class="nav-icon" src="{% static 'img/administrar.svg' %}">
              <p>
                Administrar
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url 'erp:category_list' %}" class="nav-link">
                <img class="nav-icon" src="{% static 'img/categoria.svg' %}">
                  <p> Categorias</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'erp:client_list' %}" class="nav-link">
                <img class="nav-icon" src="{% static 'img/clientes.svg' %}">
                  <p> Clientes</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="../../index3.html" class="nav-link">
                  <img class="nav-icon" src="{% static 'img/ventas.svg' %}">
                  <p> Ventas</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url 'erp:product_list' %}" class="nav-link">
                  <img class="nav-icon" src="{% static 'img/productos.svg' %}">
                  <p> Productos</p>
                </a>
              </li>
            </ul>
          </li>
{#          <li class="nav-item">#}
{#            <a href="../widgets.html" class="nav-link">#}
{#              <i class="nav-icon fas fa-th"></i>#}
{#              <p>#}
{#                Widgets#}
{#                <span class="right badge badge-danger">New</span>#}
{#              </p>#}
{#            </a>#}
{#          </li>#}


{#          <li class="nav-item menu-open">#}
{#            <a href="#" class="nav-link">#}
{#              <i class="nav-icon fas fa-copy"></i>#}
{#              <p>#}
{#                Layout Options#}
{#                <i class="fas fa-angle-left right"></i>#}
{#                <span class="badge badge-info right">6</span>#}
{#              </p>#}
{#            </a>#}
{#            <ul class="nav nav-treeview">#}
{#              <li class="nav-item">#}
{#                <a href="../layout/top-nav.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Top Navigation</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/top-nav-sidebar.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Top Navigation + Sidebar</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/boxed.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Boxed</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/fixed-sidebar.html" class="nav-link active">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Fixed Sidebar</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/fixed-sidebar-custom.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Fixed Sidebar <small>+ Custom Area</small></p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/fixed-topnav.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Fixed Navbar</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/fixed-footer.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Fixed Footer</p>#}
{#                </a>#}
{#              </li>#}
{#              <li class="nav-item">#}
{#                <a href="../layout/collapsed-sidebar.html" class="nav-link">#}
{#                  <i class="far fa-circle nav-icon"></i>#}
{#                  <p>Collapsed Sidebar</p>#}
{#                </a>#}
{#              </li>#}
{#            </ul>#}
{#          </li>#}
{#          <li class="nav-header">EXAMPLES</l  i>#}
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

app/templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        {% include 'vtc/header.html' %}
        {% include 'vtc/aside.html' %}
        <div class="content-wrapper ">
            <div class="content  mx-auto mt-2">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        {% include 'footer.html' %}
    </div>
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}';
                {#< li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
            {% endfor %}
            html += '<p>';
            Swal.fire({
                icon: 'error',
                title: 'Error',
                html: html,
            })
        {% endif %}

    </script>
    </body>
{% endblock %}

app/templates/vtc/header.html
{% load static %}
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'erp:dashboard' %}" class="nav-link">Dashboard</a>
      </li>
{#      <li class="nav-item d-none d-sm-inline-block">#}
{#        <a href="#" class="nav-link">Contact</a>#}
{#      </li>#}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
{#      <li class="nav-item dropdown">#}
{#        <a class="nav-link" data-toggle="dropdown" href="#">#}
{#          <i class="far fa-comments"></i>#}
{#          <span class="badge badge-danger navbar-badge">3</span>#}
{#        </a>#}
{#        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">#}
{#          <a href="#" class="dropdown-item">#}
{#            <!-- Message Start -->#}
{#            <div class="media">#}
{#              <img src="{% static 'lib/adminlte-3.2.0/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">#}
{#              <div class="media-body">#}
{#                <h3 class="dropdown-item-title">#}
{#                  Brad Diesel#}
{#                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>#}
{#                </h3>#}
{#                <p class="text-sm">Call me whenever you can...</p>#}
{#                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#              </div>#}
{#            </div>#}
{#            <!-- Message End -->#}
{#          </a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a href="#" class="dropdown-item">#}
{#            <!-- Message Start -->#}
{#            <div class="media">#}
{#              <img src="{% static 'lib/adminlte-3.2.0/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">#}
{#              <div class="media-body">#}
{#                <h3 class="dropdown-item-title">#}
{#                  John Pierce#}
{#                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>#}
{#                </h3>#}
{#                <p class="text-sm">I got your message bro</p>#}
{#                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#              </div>#}
{#            </div>#}
{#            <!-- Message End -->#}
{#          </a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a href="#" class="dropdown-item">#}
{#            <!-- Message Start -->#}
{#            <div class="media">#}
{#              <img src="{% static 'lib/adminlte-3.2.0/img/user4-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">#}
{#              <div class="media-body">#}
{#                <h3 class="dropdown-item-title">#}
{#                  Nora Silvester#}
{#                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>#}
{#                </h3>#}
{#                <p class="text-sm">The subject goes here</p>#}
{#                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>#}
{#              </div>#}
{#            </div>#}
{#            <!-- Message End -->#}
{#          </a>#}
{#          <div class="dropdown-divider"></div>#}
{#          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>#}
{#        </div>#}
{#      </li>#}
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="fa fa-cogs" aria-hidden="true"></i>
{#          <span class="badge badge-warning navbar-badge">15</span>#}
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">{{ user.username }}</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-address-card mr-2"></i> Editar perfil
{#            <span class="float-right text-muted text-sm">3 mins</span>#}
          </a>
          <div class="dropdown-divider"></div>
{#          <a href="#" class="dropdown-item">#}
{#            <i class="fas fa-users mr-2"></i> 8 friend requests#}
{#            <span class="float-right text-muted text-sm">12 hours</span>#}
{#          </a>#}
          <div class="dropdown-divider"></div>
          <a href="{% url 'logout' %}" class="dropdown-item">
            <i class="fa fa-reply mr-2"></i> Cerrar sesión
{#            <span class="float-right text-muted text-sm">2 days</span>#}
          </a>
          <div class="dropdown-divider"></div>
{#          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>#}
        </div>
      </li>

    </ul>
  </nav>
  <!-- /.navbar -->